---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading required packages
``` {R eval = TRUE}
library(dplyr)
library(readr)
library(ggplot2)
```

## Loading the dataset
``` {R eval = TRUE}
data <- read.csv("activity.csv")
```

## What is mean total number of steps taken per day?
``` {R eval = TRUE}
# Calculate the total number of steps taken per day
steps_by_day <- aggregate(steps ~ date, data, sum)

# Create histogram of the total number of steps taken each day
hist(steps_by_day$steps, main = paste("Total Steps Each Day"), xlab="Number of Steps")

# Calculate and print mean
mean(steps_by_day$steps)

# Calculate and print median
median(steps_by_day$steps)

```

## What is the average daily activity pattern?

``` {R eval = TRUE}

# Create a data frame of the mean and median number of steps across all days
actInterval <- data %>% dplyr::group_by(interval) %>% summarise(meanSteps = mean(steps, na.rm = TRUE))

# Generate time series plot of the intervals vs steps taken
IntervalPlot <- ggplot(
                      data = actInterval, 
                      mapping = aes(x = interval, y = meanSteps)) + 
                      geom_line() + 
                      scale_x_continuous("Day Interval",
                      breaks = seq(min(actInterval$interval), 
                                   max(actInterval$interval), 100)) +
                      scale_y_continuous("Average Number of Steps") + 
                      ggtitle("Average Number of Steps Taken by Interval"
                      )

IntervalPlot

# Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

# Return the 5 minute interval of the highest steps
actInterval[max(actInterval$meanSteps),]

```

## Imputing missing values

Note that there are a number of days/intervals where there are missing values (coded as NA). The presence of missing days may introduce bias into some calculations or summaries of the data.

``` {R eval = TRUE}
# Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NA)
summary(is.na(data))
```
Total number of NA's in the dataset is 2304. All of these are in the steps field.

To remove the bias of NA's I will be replacing all na's with the mean for that 5 minute interval. This data is already stored in my 'actInterval' data frame created earlier.
``` {R eval = TRUE}
# Create a new dataframe with a lookup/merge against the mean
datawithmean <- merge(data, actInterval, by.x = "interval")

# Replace NA's in steps with the mean value from that interval
datawithmean$steps[is.na(datawithmean$steps)] <- datawithmean$meanSteps[is.na(datawithmean$steps)]

# Rerun the NA check to ensure the NAs have been replaced
summary(is.na(datawithmean))

```

Next I will rerun the above histogram and return the mean/median values with the new dataset. This will highlight any differences that the NA's made.
``` {R eval = TRUE}
# Calculate the total number of steps taken per day
steps_by_day2 <- aggregate(steps ~ date, datawithmean, sum)

# Create histogram of the total number of steps taken each day
hist(steps_by_day2$steps, main = paste("Total Steps Each Day"), xlab="Number of Steps")

# Calculate and print mean
mean(steps_by_day2$steps)

# Calculate and print median
median(steps_by_day2$steps)

```
I can see that the NA's have slightly increased the median value. However the mean stays the same.

## Are there differences in activity patterns between weekdays and weekends?



